[package]
name = "sigma-proofs"
version = "0.1.0"

[dependencies]
ark-secp256k1 = "0.5"
ark-ec = "0.5"
ark-ff = "0.5"
ark-std = "0.5"
sha2 = "0.10"
num-bigint = "0.4.3"
rand = "0.8"
seeded-random = "0.6"
rand_core = "0.9"
rand_chacha = "0.9"
hex = "0.4.3"
